[pytest]
filterwarnings =
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore:.*PydanticDeprecatedSince20.*:DeprecationWarning
    ignore:.*extra keyword arguments on.*Field.*:DeprecationWarning
